class Const:
    X_SCREEN_SIZE = 1280
    Y_SCREEN_SIZE = 720
    BALL_SIZE = 5
    TOTAL_BALLS = 1000
    GRID_RESOLUTION = 20

    CHECK_X_MIN = BALL_SIZE
    CHECK_X_MAX = X_SCREEN_SIZE - BALL_SIZE
    CHECK_Y_MIN = BALL_SIZE
    CHECK_Y_MAX = Y_SCREEN_SIZE - BALL_SIZE
